#!/usr/bin/env python3
import os
import requests
import shutil
import time
import yaml
from datetime import datetime


def get(url, cookie, ua):
    cookies = {'session': cookie}
    headers = {'user-agent': ua}

    for i in range(3):
        try:
            r = requests.get(url, headers=headers, cookies=cookies)
            r.raise_for_status()
            print('ok', url)
            return r.text
        except Exception as e:
            print(e)
            time.sleep(1)


def prep(day, year=None):
    if year is None:
        year = datetime.now().year
    day = int(day)
    mydir = os.path.dirname(os.path.realpath(__file__))
    codes = os.path.join(mydir, 'code')
    boildir = os.path.join(codes, '.boilerplate')
    daydir = os.path.join(codes, '{:02}'.format(day))
    dayurl = 'http://adventofcode.com/{}/day/{}/input'.format(year, day)

    with open(os.path.join(mydir, '.prep'), 'r') as f:
        env = yaml.load(f)
        session_cookie = env['session_cookie']
        user_agent = env.get('user_agent', None)


    if os.path.isdir(daydir):
        print(daydir)
        yn = input('Directory already exists. Overwrite? [N/y] ')
        overwrite = yn.strip().lower() in ('y', 'yes')

        if not overwrite:
            return

        shutil.rmtree(daydir)

    shutil.copytree(boildir, daydir)
    print(daydir)

    that_moment = datetime(year, 12, day, 5)
    waiting = datetime.utcnow() < that_moment

    while datetime.utcnow() < that_moment:
        print('.', end='', flush=True)
        time.sleep(1)

    if waiting:
        print()

    problem = get(dayurl, cookie=session_cookie, ua=user_agent)

    with open(os.path.join(daydir, 'input.txt'), 'w') as f:
        f.write(problem)


if __name__ == '__main__':
    import argparse

    cli = argparse.ArgumentParser(description='Setup directory for day\'s challenge')
    cli.add_argument('day', type=int, help='Challenge day number')
    cli.add_argument('--year', type=int, default=None, help='Challenge year')

    args = cli.parse_args()

    prep(year=args.year, day=args.day)
